# H3ZMH5 | Config: I2 (lambda=0.0020, fixed tau=1.0) | seeds 1
OPTIMIZATION:
  CHECKPOINT: ""
  OUTPUT: "./optimize_output/default_fixed"
  NUM_ITERATIONS: 800
  LR: 0.02
  LOG_INTERVAL: 999
  INIT_SEQUENCE: "YVAFLKLFLETAEKHFMVGHRVHYYVFTDQPAAVPRVTLGTGRQLSVLEMGAYKRWQDVSMRRMEMISDFCERRFLSEVDYLVCVDVDMEFRDHVGVEILTPLFGTLHPSFYGSSREAFTYERRPQSQAYIPKDEGDFYYMGAFFGGSVQEVQRLTRACHQAMMVDQANGIEAVWHDESHLNKYLLRHKPTKVLSPEYLWDQQLLGWPAVLRKLRFTAVPKNHQAVRNP"
  TARGET_SMILES: "C1=CN(C(=O)NC1=O)C2C(C(C(O2)COP(=O)(O)OP(=O)(O)OC3C(C(C(C(O3)CO)O)O)O)O)O"
  FIXED_INDICES: ""
  SEED: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]
  OPTIMIZER: "adamw"
  OPTIMIZER_KWARGS: None
  PENALTY_TYPE: "kl"
  PENALTY_LAMBDA: 0.0005
  STE_INTERVAL: None
  STE_MODE: "none"
  ANNEAL: False
  ANNEALING_SCHEME: "fixed"
  TEMPERATURE: 1.0
  MIN_TEM: 1.0
  PRINT: False
  EARLY_STOP: False
  PATIENCE: 5
  USE_STE: False
  DECOUPLED_STE: False
  USE_ESMFOLD: True
  LAMBDA_STRUCT: 0.1
  PLDDT_THRESHOLD: 70.0
  PTM_THRESHOLD: 0.5
  STRUCTURE_LOSS_TYPE: "plddt"
  STRUCTURE_LOSS_FUNCTION: "relu"
  SOFTPLUS_SIGMA: 1.0
  ESMFOLD_BF16: True
  ESMFOLD_NO_RECYCLES: 3
  LR_SCHEDULER: "none"
  LR_MIN: 1e-5
  KCAT_LOSS_TYPE: "mean_only"
  KCAT_UNCERTAINTY_BETA: 0.1
