# H3ZMH5 | Config: N1 (lambda=0.0017, cosine tau=1.7->0.3) | seeds 1
OPTIMIZATION:
  CHECKPOINT: ""
  OUTPUT: "./optimize_output/default_anneal"
  NUM_ITERATIONS: 800
  LR: 0.02
  LOG_INTERVAL: 999
  INIT_SEQUENCE: "YVAFLKLFLETAEKHFMVGHRVHYYVFTDQPAAVPRVTLGTGRQLSVLEMGAYKRWQDVSMRRMEMISDFCERRFLSEVDYLVCVDVDMEFRDHVGVEILTPLFGTLHPSFYGSSREAFTYERRPQSQAYIPKDEGDFYYMGAFFGGSVQEVQRLTRACHQAMMVDQANGIEAVWHDESHLNKYLLRHKPTKVLSPEYLWDQQLLGWPAVLRKLRFTAVPKNHQAVRNP"
  TARGET_SMILES: "C1=CN(C(=O)NC1=O)C2C(C(C(O2)COP(=O)(O)OP(=O)(O)OC3C(C(C(C(O3)CO)O)O)O)O)O"
  FIXED_INDICES: ""
  SEED: [26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50]
  OPTIMIZER: "adamw"
  OPTIMIZER_KWARGS: None
  PENALTY_TYPE: "kl"
  PENALTY_LAMBDA: 0.00075
  STE_INTERVAL: None
  STE_MODE: "none"
  ANNEAL: True
  ANNEALING_SCHEME: "cosine"
  TEMPERATURE: 1.7
  MIN_TEM: 0.3
  PRINT: False
  EARLY_STOP: False
  PATIENCE: 5
  USE_STE: False
  DECOUPLED_STE: False
  USE_ESMFOLD: True
  LAMBDA_STRUCT: 0.1
  PLDDT_THRESHOLD: 70.0
  PTM_THRESHOLD: 0.5
  STRUCTURE_LOSS_TYPE: "plddt"
  STRUCTURE_LOSS_FUNCTION: "relu"
  SOFTPLUS_SIGMA: 1.0
  ESMFOLD_BF16: True
  ESMFOLD_NO_RECYCLES: 3
  LR_SCHEDULER: "none"
  LR_MIN: 1e-5
  KCAT_LOSS_TYPE: "mean_only"
  KCAT_UNCERTAINTY_BETA: 0.1
